# TODO: use a slimmer image
# image: gitpod/workspace-nix
image: gitpod/workspace-full
github:
  prebuilds:
    # enable for the default branch
    master: true
    # enable for all branches in this repo
    branches: true
    # enable for pull requests coming from this repo
    pullRequests: true
    # enable for pull requests coming from forks
    pullRequestsFromForks: false
    # add a check to pull requests
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description
    addBadge: false
vscode:
  extensions:
    - jnoortheen.nix-ide
